[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ssircapi"
version = "1.0.0"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
app = ["**",]